# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prod-check:
    #if: github.ref == 'refs/head/main'
    runs-on: ububntu-latest
    steps:
      - run: echo "Dploying to production server on branch $GITHUB_REF"
